-- Create system_assets table
CREATE TABLE IF NOT EXISTS system_assets (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    type text not null, -- e.g., 'tent_image'
    url text not null,
    name text,
    width integer,
    height integer,
    public_id text
);

-- Enable RLS
ALTER TABLE system_assets ENABLE ROW LEVEL SECURITY;

-- Policy: Everyone can read
CREATE POLICY "Public read access"
    ON system_assets FOR SELECT
    USING (true);

-- Policy: Only admins can insert/update/delete
-- Note: This relies on the profiles table having is_admin = true for the user
CREATE POLICY "Admins can insert system assets"
    ON system_assets FOR INSERT
    WITH CHECK (
        exists (
            select 1 from profiles
            where id = auth.uid()
            and is_admin = true
        )
    );

CREATE POLICY "Admins can update system assets"
    ON system_assets FOR UPDATE
    USING (
        exists (
            select 1 from profiles
            where id = auth.uid()
            and is_admin = true
        )
    );

CREATE POLICY "Admins can delete system assets"
    ON system_assets FOR DELETE
    USING (
        exists (
            select 1 from profiles
            where id = auth.uid()
            and is_admin = true
        )
    );
